---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: agressor
      image: "{{ images.agressor }}"
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
        requests:
          cpu: "500m"
          memory: 4Gi
      volumeMounts:
        - name: workspace
          mountPath: '%(prop:builddir)s/build'
        - name: logs
          mountPath: /logs
    - name: artifacts
      image: "{{ images.artifacts }}"
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "500m"
          memory: 1Gi
      command: ['/bin/sh', '-c', 'python main.py 2>&1 | tee -a /logs/artifacts.log']
      env:
        - name: RAX_ENDPOINT
          value: "%(secret:rax_endpoint)s"
        - name: RAX_PWD
          value: "%(secret:rax_pwd)s"
        - name: RAX_LOGIN
          value: "%(secret:rax_login)s"
      volumeMounts:
        - name: logs
          mountPath: /logs
    - name: proxy-cache
      image: "{{ images.cache }}"
      command: ["/bin/sh", "-c", "envsubst '${NGINX_LISTEN_PORT} ${ARTIFACTS_HOST}' < /etc/nginx/conf.d/artifacts.conf.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
      resources:
        limits:
          cpu: "1"
          memory: 3Gi
        requests:
          cpu: "500m"
          memory: 3Gi
      volumeMounts:
        - name: cache
          mountPath: /data/nginx
        - name: logs
          mountPath: /logs/
  volumes:
    - name: cache
      emptyDir: {}
    - name: workspace
      emptyDir: {}
    - name: logs
      emptyDir: {}
