---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: agressor
      image: "{{ images.agressor }}"
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "2"
          memory: 4Gi
      volumeMounts:
        - name: workspace
          mountPath: '%(prop:builddir)s/build'
    - name: artifacts
      image: "{{ images.artifacts }}"
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "2"
          memory: 4Gi
      # command: ['/start.sh', '|', 'tee', '-a', '/workspace/artifacts.log']
      env:
        - name: RAX_ENDPOINT
          value: "%(secret:rax_endpoint)s"
        - name: RAX_PWD
          value: "%(secret:rax_pwd)s"
        - name: RAX_LOGIN
          value: "%(secret:rax_login)s"
      volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: cache
          mountPath: /data/nginx
  volumes:
    - name: cache
      emptyDir: {}
    - name: workspace
      emptyDir: {}
