apiVersion: extensions/v1beta1                                                           
kind: Deployment                                                                         
metadata:                                                                                
  labels:                                                                                
    app: download                                                                          
    run: download                                                                        
  name: download                                                                        
spec:                                                                                    
  replicas: 20
  selector:                                                                              
    matchLabels:                                                                         
      run: download                                                                        
  strategy:                                                                              
    rollingUpdate:                                                                       
      maxSurge: 1                                                                        
      maxUnavailable: 1                                                                  
    type: RollingUpdate                                                                  
  template:                                                                              
    metadata:                                                                            
      labels:                                                                            
        run: download                                                                      
    spec:                                                                                
      containers:                                                                        
      - image: gcr.io/eve-dev-174712/test-thomas:download
        imagePullPolicy: Always                                                          
        name: download
      dnsPolicy: ClusterFirst                                                            
      restartPolicy: Always                                                              
      schedulerName: default-scheduler                                                   
      securityContext: {}                                                                
      terminationGracePeriodSeconds: 30                                                  
