---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.service.name }}
  labels:
    app: {{ template "fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ExternalName
  externalName: {{ .Values.artifacts.serviceName }}
  ports:
    - name: http
      port: {{ .Values.deployment.service.port }}
      targetPort: {{ .Values.artifacts.servicePort }}
      protocol: TCP
