---

version: 0.2

branches:
  user/*, feature/*, improvement/*, bugfix/*, w/*, q/*:
    stage: pre-merge

stages:
  pre-merge: 
    worker: &worker
      type: kube_pod
      path: eve/workers/pod.yaml
      images:
        worker: tests
        artifacts: "."
        fakegithub: "./tests/github-fake-config"
    steps:
    - Git: &git_pull
        name: git pull
        repourl: "%(prop:git_reference)s"
        shallow: true
        retryFetch: true
        haltOnFailure: true
    - ShellCommand:
        name: test artifacts
        command: pytest
