---
version: 0.2

branches:
  default:
    stage: pre-merge

stages:
  pre-merge:
    worker:
      type: kube_pod
      path: eve/workers/pod.yml
      images:
        artifacts: "."
        agressor: eve/workers/agressor
    steps:
    - Git: &git_pull
        name: git pull
        repourl: "%(prop:git_reference)s"
        mode: full
        method: clobber
        retryFetch: true
        haltOnFailure: true

