# Default values file for artifacts-bridge helm chart.

## nameOverride allows to change the name of the release
## rather than default value 'artifacts-bridge'
nameOverride: "artifacts-bridge"

## useShortName shorten names of Kubernetes resources.
##
##   The release name will not be included in fullname. This
##   is safe to use only if one release only is deployed
##
useShortNames: false

artifacts:
    ## servicePort designates the port of the central artifacts service.
    ##
    ##   Defaults to 80
    ##
    servicePort: 80

    ## serviceName contains the full central artifacts service path.
    ##
    ##  default: "artifacts.default.svc.cluster.local"
    ##    (adapted when artifacts chart is deployed to namespace 'default')
    ##
    serviceName: "artifacts.default.svc.cluster.local"

deployment:
  ## Configure the ingress resource that allows you to access the service.
  ingress:
    ## enabled sets the ingress record generation or not.
    ##
    ##   Defaults to false.
    ##
    enabled: false

    ## fqdn is the protocol/hostname to be covered with this ingress record.
    ##
    fqdn: "http://artifacts-bridge.local"

    ## path contains the subpath where to access the HTTP service.
    ##
    ##   Defaults to '/'.
    ##
    path: "/"

    ## tls is set to true in order to enable TLS on the ingress record.
    ##
    ##   Defaults to false.
    ##
    tls: false

    ## tlsSecret specifies a secret that contains the key/certificate for TLS
    ##
    tlsSecret: "tls-secret"

    ## annotations contains the Ingress annotations done as key:value pairs
    ##
    annotations: {}

    basicAuth:
      ## enabled specifies if basic authentication should be enabled.
      ##
      ##   This is compatible with a Nginx ingress controller only.
      ##
      enabled: False

      ## username is the basic auth login.
      ##
      username: ""

      ## passwordHash is the basic auth hashed password.
      ##
      passwordHash: ""

    whiteList:
      ## enabled specifies if IP white listing should be enabled.
      ##
      ##   This is compatible with a Nginx ingress controller only.
      ##
      enabled: False

      ## IP white list
      ##
      ips: []

  service:
    ## name will be the hostname of the local service.
    ##
    ##   (i.e. the name of the local Kubernetes service)
    ##
    ##   default: artifacts
    ##     -> service lives at http://artifacts
    ##
    name: "artifacts"

    ## port designates the local service port.
    ##
    ##   Defaults to 80
    ##     -> service lives at http://artifacts:80
    ##
    port: 80
