name: release

on:
  release:
    types: [published]

jobs:
  docker:
    uses: scality/workflows/.github/workflows/docker-build.yaml@v1
    with:
      name: artifacts
      namespace: scality
      tag: ${{ github.ref_name }}
