name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be released'
        required: true
      prerelease:
        description: "Is the release a GA?"
        required: false
        default: false
        type: boolean

jobs:
  build:
    uses: scality/workflows/.github/workflows/docker-build.yaml@v1
    with:
      name: artifacts
      namespace: scality
      tag: ${{ inputs.tag }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
          prerelease: ${{ inputs.prerelease }}
