name: Basic Tests

on:
  push:
    branches:
      - 'user/**'
      - 'feature/**'
      - 'improvement/**'
      - 'bugfix/**'
      - 'dependabot/**'
      - 'w/**'
      - 'q/**'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    strategy:
      matrix:
        image:
          - name: artifacts
            context: .
          - name: fake-github
            context: tests/github-fake-config
          - name: tests
            context: tests
    with:
      name: ${{ matrix.image.name }}
      context: ${{ matrix.image.context }}

  tests:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/${{ github.repository }}/tests:${{ github.sha }}"
      options: --user=0
    env:
      ARTIFACTS_URL: http://artifacts
    services:
      cloudserver-front:
        image: "zenko/cloudserver:8.1.2"
        env:
          REMOTE_MANAGEMENT_DISABLE: 1
          LOG_LEVEL: debug
          ENDPOINT: "cloudserver-front"
          CI: false
      fake-github-url:
        image: "ghcr.io/${{ github.repository }}/fake-github:${{ github.sha }}"
      artifacts:
        image: "ghcr.io/${{ github.repository }}/artifacts:${{ github.sha }}"
        env:
          AWS_SECRET_ACCESS_KEY: verySecretKey1
          AWS_ACCESS_KEY_ID: accessKey1
          AWS_BUCKET_PREFIX: artifacts
          ENDPOINT_URL: http://cloudserver-front:8000
          AWS_XML_NS: http://s3.amazonaws.com/doc/2006-03-01/
          GITHUB_API_URL: http://fake-github-url:5050
          GITHUB_API_COMPANY: scality
          GITHUB_API_ENABLED: "true"
          GITHUB_USER_ALLOWED_UPLOAD: "username-pass"
          BOT_USERNAME: "botuser"
          BOT_TOKEN: "botpass"
    needs:
      - publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test artifacts
        run: pytest

